    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu.Gerente;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author 68833
 */
public class MenuMostrador_Gerente extends javax.swing.JFrame {
    private Object menuEmergente;

    /**
     * Creates new form Menu
     */
    public MenuMostrador_Gerente() {
        initComponents();
        this.setLocationRelativeTo(rootPane);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuEmergente = new javax.swing.JPopupMenu();
        Acerca = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        btncomprar = new javax.swing.JButton();
        btnAgregclient = new javax.swing.JButton();
        btninfo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        menu = new javax.swing.JMenuBar();
        Registrar = new javax.swing.JMenu();
        Clientes = new javax.swing.JMenuItem();
        Proveedores = new javax.swing.JMenuItem();
        Productos = new javax.swing.JMenuItem();
        Productos1 = new javax.swing.JMenuItem();
        Productos2 = new javax.swing.JMenuItem();
        Productos3 = new javax.swing.JMenuItem();
        Productos4 = new javax.swing.JMenuItem();
        Listar = new javax.swing.JMenu();
        Client = new javax.swing.JMenuItem();
        proveedo = new javax.swing.JMenuItem();
        Product = new javax.swing.JMenuItem();
        Compras = new javax.swing.JMenuItem();
        Compras1 = new javax.swing.JMenuItem();
        Compras2 = new javax.swing.JMenuItem();
        Compras3 = new javax.swing.JMenuItem();
        Compras4 = new javax.swing.JMenuItem();
        Compras5 = new javax.swing.JMenuItem();
        Consultas = new javax.swing.JMenu();
        conCliente = new javax.swing.JCheckBoxMenuItem();
        BusCodigoProv = new javax.swing.JMenuItem();
        conCliente1 = new javax.swing.JCheckBoxMenuItem();
        conCliente2 = new javax.swing.JCheckBoxMenuItem();
        ConProducto = new javax.swing.JMenu();
        BusRangoProducto = new javax.swing.JMenuItem();
        BusCodigoProducto = new javax.swing.JMenuItem();
        BusCodigoProducto1 = new javax.swing.JMenuItem();
        Borrar = new javax.swing.JMenu();
        BorCliente = new javax.swing.JMenuItem();
        BorProveedor = new javax.swing.JMenuItem();
        BorProducto = new javax.swing.JMenuItem();
        BorCompra = new javax.swing.JMenuItem();
        BorCompra2 = new javax.swing.JMenuItem();
        BorCompra3 = new javax.swing.JMenuItem();
        BorCompra4 = new javax.swing.JMenuItem();
        Borrar1 = new javax.swing.JMenu();
        BorCliente1 = new javax.swing.JMenuItem();
        BorProveedor1 = new javax.swing.JMenuItem();
        BorProducto1 = new javax.swing.JMenuItem();
        BorCompra1 = new javax.swing.JMenuItem();
        BorCliente2 = new javax.swing.JMenuItem();
        BorCliente3 = new javax.swing.JMenuItem();
        acerca = new javax.swing.JMenu();

        MenuEmergente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuEmergenteMouseClicked(evt);
            }
        });

        Acerca.setText("Acerca de...");
        Acerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcercaActionPerformed(evt);
            }
        });
        MenuEmergente.add(Acerca);

        salir.setText("Salir");
        salir.setToolTipText("");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        MenuEmergente.add(salir);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jToolBar1.setRollover(true);

        btncomprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carrito1.png"))); // NOI18N
        btncomprar.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carrito.png"))); // NOI18N
        btncomprar.setFocusable(false);
        btncomprar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncomprar.setMargin(new java.awt.Insets(-5, 0, 0, 0));
        btncomprar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncomprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncomprarActionPerformed(evt);
            }
        });
        jToolBar1.add(btncomprar);

        btnAgregclient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo cliente1.png"))); // NOI18N
        btnAgregclient.setFocusable(false);
        btnAgregclient.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregclient.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAgregclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregclientActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAgregclient);

        btninfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/info1.png"))); // NOI18N
        btninfo.setFocusable(false);
        btninfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btninfo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btninfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninfoActionPerformed(evt);
            }
        });
        jToolBar1.add(btninfo);

        jLabel1.setText("Agregar");

        jLabel2.setText("Buscar");

        jButton1.setText("Venta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Producto");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cliente");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Pedido");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Inventario");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Producto");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/descarga.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        Registrar.setText("Registrar");

        Clientes.setText("Clientes");
        Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesActionPerformed(evt);
            }
        });
        Registrar.add(Clientes);

        Proveedores.setText("Proveedores");
        Proveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProveedoresActionPerformed(evt);
            }
        });
        Registrar.add(Proveedores);

        Productos.setText("Productos");
        Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductosActionPerformed(evt);
            }
        });
        Registrar.add(Productos);

        Productos1.setText("Empleado");
        Productos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Productos1ActionPerformed(evt);
            }
        });
        Registrar.add(Productos1);

        Productos2.setText("Pedido");
        Productos2.setToolTipText("");
        Productos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Productos2ActionPerformed(evt);
            }
        });
        Registrar.add(Productos2);

        Productos3.setText("Merma");
        Productos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Productos3ActionPerformed(evt);
            }
        });
        Registrar.add(Productos3);

        Productos4.setText("Venta");
        Productos4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Productos4ActionPerformed(evt);
            }
        });
        Registrar.add(Productos4);

        menu.add(Registrar);

        Listar.setText("Listar");

        Client.setText("Clientes");
        Client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientActionPerformed(evt);
            }
        });
        Listar.add(Client);

        proveedo.setText("Proveedor");
        proveedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedoActionPerformed(evt);
            }
        });
        Listar.add(proveedo);

        Product.setText("Producto");
        Product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductActionPerformed(evt);
            }
        });
        Listar.add(Product);

        Compras.setText("Pedido");
        Compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprasActionPerformed(evt);
            }
        });
        Listar.add(Compras);

        Compras1.setText("Empleado");
        Compras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Compras1ActionPerformed(evt);
            }
        });
        Listar.add(Compras1);

        Compras2.setText("Gerente");
        Compras2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Compras2ActionPerformed(evt);
            }
        });
        Listar.add(Compras2);

        Compras3.setText("Merma");
        Compras3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Compras3ActionPerformed(evt);
            }
        });
        Listar.add(Compras3);

        Compras4.setText("Refrigerador");
        Compras4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Compras4ActionPerformed(evt);
            }
        });
        Listar.add(Compras4);

        Compras5.setText("Registro Ventas");
        Compras5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Compras5ActionPerformed(evt);
            }
        });
        Listar.add(Compras5);

        menu.add(Listar);

        Consultas.setText("Buscar");

        conCliente.setText("Cliente");
        conCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conClienteActionPerformed(evt);
            }
        });
        Consultas.add(conCliente);

        BusCodigoProv.setText("Proveedor");
        BusCodigoProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusCodigoProvActionPerformed(evt);
            }
        });
        Consultas.add(BusCodigoProv);

        conCliente1.setText("Empleado");
        conCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conCliente1ActionPerformed(evt);
            }
        });
        Consultas.add(conCliente1);

        conCliente2.setText("Pedido");
        conCliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conCliente2ActionPerformed(evt);
            }
        });
        Consultas.add(conCliente2);

        ConProducto.setText("Producto");

        BusRangoProducto.setText("Rango de Precios");
        BusRangoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusRangoProductoActionPerformed(evt);
            }
        });
        ConProducto.add(BusRangoProducto);

        BusCodigoProducto.setText("Existencias");
        BusCodigoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusCodigoProductoActionPerformed(evt);
            }
        });
        ConProducto.add(BusCodigoProducto);

        BusCodigoProducto1.setText("Proveedor");
        BusCodigoProducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusCodigoProducto1ActionPerformed(evt);
            }
        });
        ConProducto.add(BusCodigoProducto1);

        Consultas.add(ConProducto);

        menu.add(Consultas);

        Borrar.setText("Borrar");

        BorCliente.setText("Cliente");
        BorCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorClienteActionPerformed(evt);
            }
        });
        Borrar.add(BorCliente);

        BorProveedor.setText("Proveedor");
        BorProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorProveedorActionPerformed(evt);
            }
        });
        Borrar.add(BorProveedor);

        BorProducto.setText("Producto");
        BorProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorProductoActionPerformed(evt);
            }
        });
        Borrar.add(BorProducto);

        BorCompra.setText("Pedido");
        BorCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorCompraActionPerformed(evt);
            }
        });
        Borrar.add(BorCompra);

        BorCompra2.setText("Merma");
        BorCompra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorCompra2ActionPerformed(evt);
            }
        });
        Borrar.add(BorCompra2);

        BorCompra3.setText("Empleado");
        BorCompra3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorCompra3ActionPerformed(evt);
            }
        });
        Borrar.add(BorCompra3);

        BorCompra4.setText("Venta");
        BorCompra4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorCompra4ActionPerformed(evt);
            }
        });
        Borrar.add(BorCompra4);

        menu.add(Borrar);

        Borrar1.setText("Modificar");

        BorCliente1.setText("Cliente");
        BorCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorCliente1ActionPerformed(evt);
            }
        });
        Borrar1.add(BorCliente1);

        BorProveedor1.setText("Proveedor");
        BorProveedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorProveedor1ActionPerformed(evt);
            }
        });
        Borrar1.add(BorProveedor1);

        BorProducto1.setText("Producto");
        BorProducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorProducto1ActionPerformed(evt);
            }
        });
        Borrar1.add(BorProducto1);

        BorCompra1.setText("Pedido");
        BorCompra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorCompra1ActionPerformed(evt);
            }
        });
        Borrar1.add(BorCompra1);

        BorCliente2.setText("Empleado");
        BorCliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorCliente2ActionPerformed(evt);
            }
        });
        Borrar1.add(BorCliente2);

        BorCliente3.setText("Venta");
        BorCliente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorCliente3ActionPerformed(evt);
            }
        });
        Borrar1.add(BorCliente3);

        menu.add(Borrar1);

        acerca.setText("Acerca de...");
        acerca.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                acercaAncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });
        menu.add(acerca);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(136, 136, 136))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprasActionPerformed
        listar_pedido Lrc1=new listar_pedido();
        this.setVisible(false);
        Lrc1.setVisible(true);
    }//GEN-LAST:event_ComprasActionPerformed

    private void BusCodigoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusCodigoProductoActionPerformed
        // TODO add your handling code here:
         buscar_producto_exis bp1=new buscar_producto_exis();
        this.setVisible(false);
        bp1.setVisible(true);            
    }//GEN-LAST:event_BusCodigoProductoActionPerformed

    private void BorProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorProveedorActionPerformed
        // TODO add your handling code here:
        borrar_proveedor Bp1=new borrar_proveedor();
        this.setVisible(false);
        Bp1.setVisible(true);
    }//GEN-LAST:event_BorProveedorActionPerformed

    private void MenuEmergenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuEmergenteMouseClicked
       
    }//GEN-LAST:event_MenuEmergenteMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
         if(evt.getButton()==3)
        {
            MenuEmergente.show(this, evt.getX(),evt.getY());
        }
    }//GEN-LAST:event_formMouseClicked

    private void AcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcercaActionPerformed
        JOptionPane.showMessageDialog(null,"Acerca de...\n SISTEMA ADMINISTADROR DE TIENDA  v0.6\n Elaborado por :\n Calva Hernández José Manuel\n Ruiz Lopez Luis Carlos7" );
    }//GEN-LAST:event_AcercaActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
       this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        int x;
        x=JOptionPane.showConfirmDialog(rootPane, "¿Desea realmente salir del sistema?","Salir del sistema",JOptionPane.YES_NO_OPTION);
        if(x==0)
        {
            System.exit(0);
        }
        else
        {
            System.out.println("Continuemos...");
        }
    }//GEN-LAST:event_salirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        int x;
        x=JOptionPane.showConfirmDialog(rootPane, "¿Desea realmente salir del sistema?","Salir del sistema",JOptionPane.YES_NO_OPTION);
        if(x==0)
        {
            System.exit(0);
        }
        else
        {
            System.out.println("Continuemos...");
        }
    }//GEN-LAST:event_formWindowClosing

    private void ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesActionPerformed
        // TODO add your handling code here:
        agreg_cliente agcl1=new agreg_cliente();
        this.setVisible(false);
        agcl1.setVisible(true);        
    }//GEN-LAST:event_ClientesActionPerformed

    private void ProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProveedoresActionPerformed
        // TODO add your handling code here:
        agreg_prov ags1=new agreg_prov();
        this.setVisible(false);
        ags1.setVisible(true);
    }//GEN-LAST:event_ProveedoresActionPerformed

    private void ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductosActionPerformed
        // TODO add your handling code here:
        agreg_product agp1=new agreg_product();
        this.setVisible(false);
        agp1.setVisible(true);
    }//GEN-LAST:event_ProductosActionPerformed

    private void BusCodigoProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusCodigoProvActionPerformed
        // TODO add your handling code here:
        buscar_prov bs1=new buscar_prov();
        this.setVisible(false);
        bs1.setVisible(true);
    }//GEN-LAST:event_BusCodigoProvActionPerformed

    private void BusRangoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusRangoProductoActionPerformed
        // TODO add your handling code here:
        buscar_product_rango brp1=new buscar_product_rango();
        this.setVisible(false);
        brp1.setVisible(true);
    }//GEN-LAST:event_BusRangoProductoActionPerformed

    private void ClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientActionPerformed
        // TODO add your handling code here:
        listar_clientes lc1=new listar_clientes();
        this.setVisible(false);
        lc1.setVisible(true);
    }//GEN-LAST:event_ClientActionPerformed

    private void proveedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedoActionPerformed
        // TODO add your handling code here:
        listar_prov Ls1=new listar_prov();
        this.setVisible(false);
        Ls1.setVisible(true);
    }//GEN-LAST:event_proveedoActionPerformed

    private void ProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductActionPerformed
        // TODO add your handling code here:
        lista_product Lp1=new lista_product();
        this.setVisible(false);
        Lp1.setVisible(true);
    }//GEN-LAST:event_ProductActionPerformed

    private void btncomprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncomprarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        agreg_venta av=new agreg_venta();
        av.setVisible(true);
    }//GEN-LAST:event_btncomprarActionPerformed

    private void btninfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninfoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Acerca de...\n SISTEMA ADMINISTADROR DE TIENDA  v1.0\n Elaborado por :\n Calva Hernández José Manuel\n Ruiz Lopez Luis Carlos7" );
    }//GEN-LAST:event_btninfoActionPerformed

    private void btnAgregclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregclientActionPerformed
        // TODO add your handling code here:
        agreg_cliente agcl1=new agreg_cliente();
        this.setVisible(false);
        agcl1.setVisible(true); 
    }//GEN-LAST:event_btnAgregclientActionPerformed

    private void BorClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorClienteActionPerformed
        // TODO add your handling code here:
        borrar_cliente Bc1=new borrar_cliente();
        this.setVisible(false);
        Bc1.setVisible(true);
    }//GEN-LAST:event_BorClienteActionPerformed

    private void BorProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorProductoActionPerformed
        // TODO add your handling code here:
        borrar_product Bp1=new borrar_product();
        this.setVisible(false);
        Bp1.setVisible(true);
    }//GEN-LAST:event_BorProductoActionPerformed

    private void BorCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorCompraActionPerformed
        // TODO add your handling code here:
        borrar_pedido Bc1=new borrar_pedido();
        this.setVisible(false);
        Bc1.setVisible(true);
    }//GEN-LAST:event_BorCompraActionPerformed

    private void conClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conClienteActionPerformed
        // TODO add your handling code here:
        buscar_cliente bc1=new buscar_cliente();
        this.setVisible(false);
        bc1.setVisible(true);
    }//GEN-LAST:event_conClienteActionPerformed

    private void acercaAncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_acercaAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_acercaAncestorMoved

    private void BorCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorCliente1ActionPerformed
        // TODO add your handling code here:
        actualizar_cliente acl=new actualizar_cliente();
        this.setVisible(false);
        acl.setVisible(true);
    }//GEN-LAST:event_BorCliente1ActionPerformed

    private void BorProveedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorProveedor1ActionPerformed
        // TODO add your handling code here:
        actualizar_prov acl=new actualizar_prov();
        this.setVisible(false);
        acl.setVisible(true);
    }//GEN-LAST:event_BorProveedor1ActionPerformed

    private void BorProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorProducto1ActionPerformed
        // TODO add your handling code here:
        actualizar_product acl=new actualizar_product();
        this.setVisible(false);
        acl.setVisible(true);
    }//GEN-LAST:event_BorProducto1ActionPerformed

    private void BorCompra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorCompra1ActionPerformed
        // TODO add your handling code here:
        actualizar_pedido acl=new actualizar_pedido();
        this.setVisible(false);
        acl.setVisible(true);
    }//GEN-LAST:event_BorCompra1ActionPerformed

    private void Productos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Productos1ActionPerformed
        // TODO add your handling code here:
        agreg_mostrador agcl1=new agreg_mostrador();
        this.setVisible(false);
        agcl1.setVisible(true); 
    }//GEN-LAST:event_Productos1ActionPerformed

    private void Productos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Productos2ActionPerformed
        // TODO add your handling code here:
        agreg_pedido agcl1=new agreg_pedido();
        this.setVisible(false);
        agcl1.setVisible(true); 
    }//GEN-LAST:event_Productos2ActionPerformed

    private void Productos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Productos3ActionPerformed
        // TODO add your handling code here:
        agreg_merma agcl1=new agreg_merma();
        this.setVisible(false);
        agcl1.setVisible(true); 
    }//GEN-LAST:event_Productos3ActionPerformed

    private void Productos4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Productos4ActionPerformed
        // TODO add your handling code here:
        agreg_venta agcl1=new agreg_venta();
        this.setVisible(false);
        agcl1.setVisible(true); 
    }//GEN-LAST:event_Productos4ActionPerformed

    private void Compras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Compras1ActionPerformed
        // TODO add your handling code here:
        listar_mostrador lc1=new listar_mostrador();
        this.setVisible(false);
        lc1.setVisible(true);
    }//GEN-LAST:event_Compras1ActionPerformed

    private void Compras2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Compras2ActionPerformed
        // TODO add your handling code here:
        listar_gerentes lc1=new listar_gerentes();
        this.setVisible(false);
        lc1.setVisible(true);
    }//GEN-LAST:event_Compras2ActionPerformed

    private void Compras3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Compras3ActionPerformed
        // TODO add your handling code here:
        listar_merma lc1=new listar_merma();
        this.setVisible(false);
        lc1.setVisible(true);
    }//GEN-LAST:event_Compras3ActionPerformed

    private void Compras4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Compras4ActionPerformed
        // TODO add your handling code here:
        listar_refri lc1=new listar_refri();
        this.setVisible(false);
        lc1.setVisible(true);
    }//GEN-LAST:event_Compras4ActionPerformed

    private void Compras5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Compras5ActionPerformed
        // TODO add your handling code here:}
        listar_reg_venta lc1=new listar_reg_venta();
        this.setVisible(false);
        lc1.setVisible(true);
    }//GEN-LAST:event_Compras5ActionPerformed

    private void conCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conCliente1ActionPerformed
        // TODO add your handling code here:
        buscar_empleado bc1=new buscar_empleado();
        this.setVisible(false);
        bc1.setVisible(true);
    }//GEN-LAST:event_conCliente1ActionPerformed

    private void conCliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conCliente2ActionPerformed
        // TODO add your handling code here:
        buscar_pedido bc1=new buscar_pedido();
        this.setVisible(false);
        bc1.setVisible(true);
    }//GEN-LAST:event_conCliente2ActionPerformed

    private void BusCodigoProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusCodigoProducto1ActionPerformed
        // TODO add your handling code here:
        buscar_producto_prov bc1=new buscar_producto_prov();
        this.setVisible(false);
        bc1.setVisible(true);
    }//GEN-LAST:event_BusCodigoProducto1ActionPerformed

    private void BorCompra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorCompra2ActionPerformed
        // TODO add your handling code here:
        borrar_merma Bc1=new borrar_merma();
        this.setVisible(false);
        Bc1.setVisible(true);
    }//GEN-LAST:event_BorCompra2ActionPerformed

    private void BorCompra3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorCompra3ActionPerformed
        // TODO add your handling code here:
        borrar_mostrador Bc1=new borrar_mostrador();
        this.setVisible(false);
        Bc1.setVisible(true);
    }//GEN-LAST:event_BorCompra3ActionPerformed

    private void BorCompra4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorCompra4ActionPerformed
        // TODO add your handling code here:
        borrar_venta Bc1=new borrar_venta();
        this.setVisible(false);
        Bc1.setVisible(true);
    }//GEN-LAST:event_BorCompra4ActionPerformed

    private void BorCliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorCliente2ActionPerformed
        // TODO add your handling code here:
        actualizar_mostrador acl=new actualizar_mostrador();
        this.setVisible(false);
        acl.setVisible(true);
    }//GEN-LAST:event_BorCliente2ActionPerformed

    private void BorCliente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorCliente3ActionPerformed
        // TODO add your handling code here:
        actualizar_venta acl=new actualizar_venta();
        this.setVisible(false);
        acl.setVisible(true);
    }//GEN-LAST:event_BorCliente3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        agreg_venta av = new agreg_venta();

        av.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        agreg_prod_ped apg = new agreg_prod_ped();

        apg.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        buscar_cliente bc = new buscar_cliente();

        bc.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        buscar_pedido bp = new buscar_pedido();

        bp.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        buscar_producto_exis bpe = new buscar_producto_exis();

        bpe.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        buscar_product_rango bpr = new buscar_product_rango();

        bpr.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        new MenuGerente().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMostrador_Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMostrador_Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMostrador_Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMostrador_Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMostrador_Gerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Acerca;
    private javax.swing.JMenuItem BorCliente;
    private javax.swing.JMenuItem BorCliente1;
    private javax.swing.JMenuItem BorCliente2;
    private javax.swing.JMenuItem BorCliente3;
    private javax.swing.JMenuItem BorCompra;
    private javax.swing.JMenuItem BorCompra1;
    private javax.swing.JMenuItem BorCompra2;
    private javax.swing.JMenuItem BorCompra3;
    private javax.swing.JMenuItem BorCompra4;
    private javax.swing.JMenuItem BorProducto;
    private javax.swing.JMenuItem BorProducto1;
    private javax.swing.JMenuItem BorProveedor;
    private javax.swing.JMenuItem BorProveedor1;
    private javax.swing.JMenu Borrar;
    private javax.swing.JMenu Borrar1;
    private javax.swing.JMenuItem BusCodigoProducto;
    private javax.swing.JMenuItem BusCodigoProducto1;
    private javax.swing.JMenuItem BusCodigoProv;
    private javax.swing.JMenuItem BusRangoProducto;
    private javax.swing.JMenuItem Client;
    private javax.swing.JMenuItem Clientes;
    private javax.swing.JMenuItem Compras;
    private javax.swing.JMenuItem Compras1;
    private javax.swing.JMenuItem Compras2;
    private javax.swing.JMenuItem Compras3;
    private javax.swing.JMenuItem Compras4;
    private javax.swing.JMenuItem Compras5;
    private javax.swing.JMenu ConProducto;
    private javax.swing.JMenu Consultas;
    private javax.swing.JMenu Listar;
    private javax.swing.JPopupMenu MenuEmergente;
    private javax.swing.JMenuItem Product;
    private javax.swing.JMenuItem Productos;
    private javax.swing.JMenuItem Productos1;
    private javax.swing.JMenuItem Productos2;
    private javax.swing.JMenuItem Productos3;
    private javax.swing.JMenuItem Productos4;
    private javax.swing.JMenuItem Proveedores;
    private javax.swing.JMenu Registrar;
    private javax.swing.JMenu acerca;
    private javax.swing.JButton btnAgregclient;
    private javax.swing.JButton btncomprar;
    private javax.swing.JButton btninfo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBoxMenuItem conCliente;
    private javax.swing.JCheckBoxMenuItem conCliente1;
    private javax.swing.JCheckBoxMenuItem conCliente2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem proveedo;
    private javax.swing.JMenuItem salir;
    // End of variables declaration//GEN-END:variables
}
