    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu.Mostrador;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import menu.Sesion;

/**
 *
 * @author 68833
 */
public class MenuSimple extends javax.swing.JFrame {
    private Object menuEmergente;

    /**
     * Creates new form Menu
     */
    public MenuSimple() {
        initComponents();
        this.setLocationRelativeTo(rootPane);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuEmergente = new javax.swing.JPopupMenu();
        Acerca = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        btncomprar = new javax.swing.JButton();
        btninfo = new javax.swing.JButton();
        menu = new javax.swing.JMenuBar();
        Registrar = new javax.swing.JMenu();
        Productos = new javax.swing.JMenuItem();
        Clientes = new javax.swing.JMenuItem();
        Listar = new javax.swing.JMenu();
        Product = new javax.swing.JMenuItem();
        Client = new javax.swing.JMenuItem();
        Consultas = new javax.swing.JMenu();
        conCliente = new javax.swing.JCheckBoxMenuItem();
        ConProducto = new javax.swing.JMenu();
        BusRangoProducto = new javax.swing.JMenuItem();
        BusCodigoProducto = new javax.swing.JMenuItem();
        ConCompras = new javax.swing.JMenu();
        BusCodigoProdCompras = new javax.swing.JMenuItem();
        acerca1 = new javax.swing.JMenu();
        conCliente4 = new javax.swing.JCheckBoxMenuItem();
        acerca = new javax.swing.JMenu();
        conCliente3 = new javax.swing.JCheckBoxMenuItem();

        MenuEmergente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuEmergenteMouseClicked(evt);
            }
        });

        Acerca.setText("Acerca de...");
        Acerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcercaActionPerformed(evt);
            }
        });
        MenuEmergente.add(Acerca);

        salir.setText("Salir");
        salir.setToolTipText("");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        MenuEmergente.add(salir);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jToolBar1.setRollover(true);

        btncomprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carrito1.png"))); // NOI18N
        btncomprar.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carrito.png"))); // NOI18N
        btncomprar.setFocusable(false);
        btncomprar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncomprar.setMargin(new java.awt.Insets(-5, 0, 0, 0));
        btncomprar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncomprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncomprarActionPerformed(evt);
            }
        });
        jToolBar1.add(btncomprar);

        btninfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/info1.png"))); // NOI18N
        btninfo.setFocusable(false);
        btninfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btninfo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btninfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninfoActionPerformed(evt);
            }
        });
        jToolBar1.add(btninfo);

        Registrar.setText("Registrar");

        Productos.setText("Productos");
        Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductosActionPerformed(evt);
            }
        });
        Registrar.add(Productos);

        Clientes.setText("Venta");
        Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesActionPerformed(evt);
            }
        });
        Registrar.add(Clientes);

        menu.add(Registrar);

        Listar.setText("Listar");

        Product.setText("Producto");
        Product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductActionPerformed(evt);
            }
        });
        Listar.add(Product);

        Client.setText("Clientes");
        Client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientActionPerformed(evt);
            }
        });
        Listar.add(Client);

        menu.add(Listar);

        Consultas.setText("Buscar");

        conCliente.setText("Cliente");
        conCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conClienteActionPerformed(evt);
            }
        });
        Consultas.add(conCliente);

        ConProducto.setText("Producto");

        BusRangoProducto.setText("Existencia");
        BusRangoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusRangoProductoActionPerformed(evt);
            }
        });
        ConProducto.add(BusRangoProducto);

        BusCodigoProducto.setText("Codigo");
        BusCodigoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusCodigoProductoActionPerformed(evt);
            }
        });
        ConProducto.add(BusCodigoProducto);

        Consultas.add(ConProducto);

        ConCompras.setText("Pedido");

        BusCodigoProdCompras.setText("idPedido");
        BusCodigoProdCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusCodigoProdComprasActionPerformed(evt);
            }
        });
        ConCompras.add(BusCodigoProdCompras);

        Consultas.add(ConCompras);

        menu.add(Consultas);

        acerca1.setText("Sesión");
        acerca1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                acerca1AncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        conCliente4.setText("Cerrar sesión");
        conCliente4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conCliente4ActionPerformed(evt);
            }
        });
        acerca1.add(conCliente4);

        menu.add(acerca1);

        acerca.setText("Acerca de...");
        acerca.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                acercaAncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });

        conCliente3.setText("Punto de Venta");
        conCliente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conCliente3ActionPerformed(evt);
            }
        });
        acerca.add(conCliente3);

        menu.add(acerca);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 276, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BusCodigoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusCodigoProductoActionPerformed
        // TODO add your handling code here:
         buscar_product_rango bp1=new buscar_product_rango();
        this.setVisible(false);
        bp1.setVisible(true);            
    }//GEN-LAST:event_BusCodigoProductoActionPerformed

    private void MenuEmergenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuEmergenteMouseClicked
       
    }//GEN-LAST:event_MenuEmergenteMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
         if(evt.getButton()==3)
        {
            MenuEmergente.show(this, evt.getX(),evt.getY());
        }
    }//GEN-LAST:event_formMouseClicked

    private void AcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcercaActionPerformed
        JOptionPane.showMessageDialog(null, "Acerca de...\n SISTEMA ADMINISTRADOR DE TIENDA  v1.0\n Elaborado por :\n Calva Hernández José Manuel\n De la Rosa Gutiérrez Kaleb Yael\n Ruiz Lopez Luis Carlos");
    }//GEN-LAST:event_AcercaActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
       this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        int x;
        x=JOptionPane.showConfirmDialog(rootPane, "¿Desea realmente salir del sistema?","Salir del sistema",JOptionPane.YES_NO_OPTION);
        if(x==0)
        {
            System.exit(0);
        }
        else
        {
            System.out.println("Continuemos...");
        }
    }//GEN-LAST:event_salirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        int x;
        x=JOptionPane.showConfirmDialog(rootPane, "¿Desea realmente salir del sistema?","Salir del sistema",JOptionPane.YES_NO_OPTION);
        if(x==0)
        {
            System.exit(0);
        }
        else
        {
            System.out.println("Continuemos...");
        }
    }//GEN-LAST:event_formWindowClosing

    private void ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        agreg_venta agcl1=new agreg_venta();
        agcl1.setVisible(true);
        
    }//GEN-LAST:event_ClientesActionPerformed

    private void ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductosActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        agreg_prod_ped agp1=new agreg_prod_ped();
        
        agp1.setVisible(true);
    }//GEN-LAST:event_ProductosActionPerformed

    private void BusRangoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusRangoProductoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        buscar_producto_exis brp1=new buscar_producto_exis();
        
        brp1.setVisible(true);
    }//GEN-LAST:event_BusRangoProductoActionPerformed

    private void ClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        listar_clientes lc1=new listar_clientes();
        
        lc1.setVisible(true);
    }//GEN-LAST:event_ClientActionPerformed

    private void ProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        lista_product Lp1=new lista_product();
        
        Lp1.setVisible(true);
    }//GEN-LAST:event_ProductActionPerformed

    private void btncomprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncomprarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        agreg_venta av=new agreg_venta();
        
        av.setVisible(true);
    }//GEN-LAST:event_btncomprarActionPerformed

    private void btninfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninfoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Acerca de...\n SISTEMA ADMINISTRADOR DE TIENDA  v1.0\n Elaborado por :\n Calva Hernández José Manuel\n De la Rosa Gutiérrez Kaleb Yael\n Ruiz Lopez Luis Carlos" );
    }//GEN-LAST:event_btninfoActionPerformed

    private void BusCodigoProdComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusCodigoProdComprasActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        buscar_pedido bc1=new buscar_pedido();
        
        bc1.setVisible(true);
    }//GEN-LAST:event_BusCodigoProdComprasActionPerformed

    private void conClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conClienteActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        buscar_cliente bc2 = new buscar_cliente();
        
        bc2.setVisible(true);
    }//GEN-LAST:event_conClienteActionPerformed

    private void acercaAncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_acercaAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_acercaAncestorMoved

    private void conCliente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conCliente3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Acerca de...\n SISTEMA ADMINISTRADOR DE TIENDA  v1.0\n Elaborado por :\n Calva Hernández José Manuel\n De la Rosa Gutiérrez Kaleb Yael\n Ruiz Lopez Luis Carlos" );
    }//GEN-LAST:event_conCliente3ActionPerformed

    private void conCliente4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conCliente4ActionPerformed
        // TODO add your handling code here:
        new Sesion().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_conCliente4ActionPerformed

    private void acerca1AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_acerca1AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_acerca1AncestorMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuSimple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuSimple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuSimple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuSimple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuSimple().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Acerca;
    private javax.swing.JMenuItem BusCodigoProdCompras;
    private javax.swing.JMenuItem BusCodigoProducto;
    private javax.swing.JMenuItem BusRangoProducto;
    private javax.swing.JMenuItem Client;
    private javax.swing.JMenuItem Clientes;
    private javax.swing.JMenu ConCompras;
    private javax.swing.JMenu ConProducto;
    private javax.swing.JMenu Consultas;
    private javax.swing.JMenu Listar;
    private javax.swing.JPopupMenu MenuEmergente;
    private javax.swing.JMenuItem Product;
    private javax.swing.JMenuItem Productos;
    private javax.swing.JMenu Registrar;
    private javax.swing.JMenu acerca;
    private javax.swing.JMenu acerca1;
    private javax.swing.JButton btncomprar;
    private javax.swing.JButton btninfo;
    private javax.swing.JCheckBoxMenuItem conCliente;
    private javax.swing.JCheckBoxMenuItem conCliente3;
    private javax.swing.JCheckBoxMenuItem conCliente4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem salir;
    // End of variables declaration//GEN-END:variables
}
