    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu.Mostrador;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author 68833
 */
public class MenuMostrador extends javax.swing.JFrame {
    private Object menuEmergente;

    /**
     * Creates new form Menu
     */
    public MenuMostrador() {
        initComponents();
        this.setLocationRelativeTo(rootPane);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuEmergente = new javax.swing.JPopupMenu();
        Acerca = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        btncomprar = new javax.swing.JButton();
        btninfo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        menu = new javax.swing.JMenuBar();
        Registrar = new javax.swing.JMenu();
        Productos = new javax.swing.JMenuItem();
        Clientes = new javax.swing.JMenuItem();
        Listar = new javax.swing.JMenu();
        Product = new javax.swing.JMenuItem();
        Client = new javax.swing.JMenuItem();
        Consultas = new javax.swing.JMenu();
        conCliente = new javax.swing.JCheckBoxMenuItem();
        ConProducto = new javax.swing.JMenu();
        BusRangoProducto = new javax.swing.JMenuItem();
        BusCodigoProducto = new javax.swing.JMenuItem();
        ConCompras = new javax.swing.JMenu();
        BusCodigoProdCompras = new javax.swing.JMenuItem();
        acerca = new javax.swing.JMenu();

        MenuEmergente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuEmergenteMouseClicked(evt);
            }
        });

        Acerca.setText("Acerca de...");
        Acerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcercaActionPerformed(evt);
            }
        });
        MenuEmergente.add(Acerca);

        salir.setText("Salir");
        salir.setToolTipText("");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        MenuEmergente.add(salir);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jToolBar1.setRollover(true);

        btncomprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carrito1.png"))); // NOI18N
        btncomprar.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carrito.png"))); // NOI18N
        btncomprar.setFocusable(false);
        btncomprar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncomprar.setMargin(new java.awt.Insets(-5, 0, 0, 0));
        btncomprar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncomprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncomprarActionPerformed(evt);
            }
        });
        jToolBar1.add(btncomprar);

        btninfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/info1.png"))); // NOI18N
        btninfo.setFocusable(false);
        btninfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btninfo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btninfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninfoActionPerformed(evt);
            }
        });
        jToolBar1.add(btninfo);

        jLabel1.setText("Agregar");

        jLabel2.setText("Buscar");

        jButton1.setText("Venta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Producto");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cliente");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Pedido");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Inventario");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Producto");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        Registrar.setText("Registrar");

        Productos.setText("Productos");
        Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductosActionPerformed(evt);
            }
        });
        Registrar.add(Productos);

        Clientes.setText("Venta");
        Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesActionPerformed(evt);
            }
        });
        Registrar.add(Clientes);

        menu.add(Registrar);

        Listar.setText("Listar");

        Product.setText("Producto");
        Product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductActionPerformed(evt);
            }
        });
        Listar.add(Product);

        Client.setText("Clientes");
        Client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientActionPerformed(evt);
            }
        });
        Listar.add(Client);

        menu.add(Listar);

        Consultas.setText("Buscar");

        conCliente.setText("Cliente");
        conCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conClienteActionPerformed(evt);
            }
        });
        Consultas.add(conCliente);

        ConProducto.setText("Producto");

        BusRangoProducto.setText("Existencia");
        BusRangoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusRangoProductoActionPerformed(evt);
            }
        });
        ConProducto.add(BusRangoProducto);

        BusCodigoProducto.setText("Codigo");
        BusCodigoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusCodigoProductoActionPerformed(evt);
            }
        });
        ConProducto.add(BusCodigoProducto);

        Consultas.add(ConProducto);

        ConCompras.setText("Pedido");

        BusCodigoProdCompras.setText("idPedido");
        BusCodigoProdCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusCodigoProdComprasActionPerformed(evt);
            }
        });
        ConCompras.add(BusCodigoProdCompras);

        Consultas.add(ConCompras);

        menu.add(Consultas);

        acerca.setText("Acerca de...");
        acerca.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                acercaAncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });
        menu.add(acerca);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(214, 214, 214))
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BusCodigoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusCodigoProductoActionPerformed
        // TODO add your handling code here:
         buscar_product_rango bp1=new buscar_product_rango();
        this.setVisible(false);
        bp1.setVisible(true);            
    }//GEN-LAST:event_BusCodigoProductoActionPerformed

    private void MenuEmergenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuEmergenteMouseClicked
       
    }//GEN-LAST:event_MenuEmergenteMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
         if(evt.getButton()==3)
        {
            MenuEmergente.show(this, evt.getX(),evt.getY());
        }
    }//GEN-LAST:event_formMouseClicked

    private void AcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcercaActionPerformed
        JOptionPane.showMessageDialog(null, "Creadores:\n Calva Hernández José Manuel \n Ruiz Lopez Luis Carlos\n Proyecto: Sistema Punto de Venta\n Version: 0.6");
    }//GEN-LAST:event_AcercaActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
       this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        int x;
        x=JOptionPane.showConfirmDialog(rootPane, "¿Desea realmente salir del sistema?","Salir del sistema",JOptionPane.YES_NO_OPTION);
        if(x==0)
        {
            System.exit(0);
        }
        else
        {
            System.out.println("Continuemos...");
        }
    }//GEN-LAST:event_salirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        int x;
        x=JOptionPane.showConfirmDialog(rootPane, "¿Desea realmente salir del sistema?","Salir del sistema",JOptionPane.YES_NO_OPTION);
        if(x==0)
        {
            System.exit(0);
        }
        else
        {
            System.out.println("Continuemos...");
        }
    }//GEN-LAST:event_formWindowClosing

    private void ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        agreg_venta agcl1=new agreg_venta();
        agcl1.setVisible(true);
        
    }//GEN-LAST:event_ClientesActionPerformed

    private void ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductosActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        agreg_prod_ped agp1=new agreg_prod_ped();
        
        agp1.setVisible(true);
    }//GEN-LAST:event_ProductosActionPerformed

    private void BusRangoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusRangoProductoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        buscar_producto_exis brp1=new buscar_producto_exis();
        
        brp1.setVisible(true);
    }//GEN-LAST:event_BusRangoProductoActionPerformed

    private void ClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        listar_clientes lc1=new listar_clientes();
        
        lc1.setVisible(true);
    }//GEN-LAST:event_ClientActionPerformed

    private void ProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        lista_product Lp1=new lista_product();
        
        Lp1.setVisible(true);
    }//GEN-LAST:event_ProductActionPerformed

    private void btncomprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncomprarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        agreg_venta av=new agreg_venta();
        
        av.setVisible(true);
    }//GEN-LAST:event_btncomprarActionPerformed

    private void btninfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninfoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Acerca de...\n SISTEMA ADMINISTADROR DE TIENDA  v0.6\n Elaborado por :\n Calva Hernández José Manuel\n Ruiz Lopez Luis Carlos7" );
    }//GEN-LAST:event_btninfoActionPerformed

    private void BusCodigoProdComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusCodigoProdComprasActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        buscar_pedido bc1=new buscar_pedido();
        
        bc1.setVisible(true);
    }//GEN-LAST:event_BusCodigoProdComprasActionPerformed

    private void conClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conClienteActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        buscar_cliente bc2 = new buscar_cliente();
        
        bc2.setVisible(true);
    }//GEN-LAST:event_conClienteActionPerformed

    private void acercaAncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_acercaAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_acercaAncestorMoved

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        agreg_prod_ped apg = new agreg_prod_ped();
       
        apg.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        agreg_venta av = new agreg_venta();
       
        av.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        buscar_product_rango bpr = new buscar_product_rango();
        
        bpr.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        buscar_producto_exis bpe = new buscar_producto_exis();
        
        bpe.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        buscar_cliente bc = new buscar_cliente();
        
        bc.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       this.dispose();
        buscar_pedido bp = new buscar_pedido();
        
        bp.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMostrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMostrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMostrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMostrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMostrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Acerca;
    private javax.swing.JMenuItem BusCodigoProdCompras;
    private javax.swing.JMenuItem BusCodigoProducto;
    private javax.swing.JMenuItem BusRangoProducto;
    private javax.swing.JMenuItem Client;
    private javax.swing.JMenuItem Clientes;
    private javax.swing.JMenu ConCompras;
    private javax.swing.JMenu ConProducto;
    private javax.swing.JMenu Consultas;
    private javax.swing.JMenu Listar;
    private javax.swing.JPopupMenu MenuEmergente;
    private javax.swing.JMenuItem Product;
    private javax.swing.JMenuItem Productos;
    private javax.swing.JMenu Registrar;
    private javax.swing.JMenu acerca;
    private javax.swing.JButton btncomprar;
    private javax.swing.JButton btninfo;
    private javax.swing.JCheckBoxMenuItem conCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem salir;
    // End of variables declaration//GEN-END:variables
}
